
a:
	g++-11 -o out A.cpp
	./out
b:
	g++ -o out B.cpp
	./out
c:
	g++ -o out C.cpp
	./out
d:
	g++ -o out D.cpp
	./out
e:
	g++ -o out E.cpp
	./out
f:
	g++ -o out F.cpp
	./out
g:
	g++ -o out G.cpp
	./out
t:
	g++ -o out template.cpp
	./out

clean:
	rm out