
GPP=g++ -std=c++2a
OUT=-o out

a:
	${GPP} ${OUT} A.cpp
	./out
b:
	${GPP} ${OUT} B.cpp
	./out
c:
	${GPP} ${OUT} C.cpp
	./out
d:
	${GPP} ${OUT} D.cpp
	./out
e:
	${GPP} ${OUT} E.cpp
	./out
f:
	${GPP} ${OUT} F.cpp
	./out
g:
	${GPP} ${OUT} G.cpp
	./out
t:
	${GPP} ${OUT} template.cpp
	./out

clean:
	rm out